#!/bin/sh
#
# Start the WiFi network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting Wifi driver: "
	modprobe brcmfmac
	wpa_supplicant -B -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf
	udhcpc -b -i wlan0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping Wifi driver: "
	modprobe -r brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
